# scripts/compute_ground_truth.py

import json
from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA_JSON = ROOT / "01_Dataset" / "SU_Football_Offense_2021_2024.json"
OUT_CSV = ROOT / "04_Analysis" / "ground_truth_players.csv"
OUT_MD = ROOT / "04_Analysis" / "ground_truth_summary.md"


def zscore(series: pd.Series) -> pd.Series:
    m = series.mean()
    s = series.std(ddof=0)
    if s == 0:
        return pd.Series(0.0, index=series.index)
    return (series - m) / s


def main():
    if not DATA_JSON.exists():
        raise FileNotFoundError(
            f"Expected anonymized dataset at {DATA_JSON}. Run build_anonymized_dataset.py first."
        )

    with DATA_JSON.open("r", encoding="utf-8") as f:
        records = json.load(f)

    df = pd.DataFrame(records)

    if df.empty:
        raise ValueError("Anonymized dataset is empty.")

    # Compute z-scores for composite performance
    df["z_yards"] = zscore(df["total_yards"])
    df["z_td"] = zscore(df["touchdowns"])
    df["z_eff"] = zscore(df["efficiency_metric"])

    df["composite_score"] = df["z_yards"] + df["z_td"] + df["z_eff"]

    # Ranks: 1 = best
    df["impact_rank"] = df["composite_score"].rank(ascending=False, method="min").astype(int)
    df["efficiency_rank"] = df["efficiency_metric"].rank(ascending=False, method="min").astype(int)
    df["usage_rank"] = df["targets_or_touches"].rank(ascending=False, method="min").astype(int)

    # Save full table
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)

    # Build a short markdown summary of top/bottom players
    lines = []
    lines.append("# Ground Truth Summary\n")
    lines.append("This file is auto-generated by `scripts/compute_ground_truth.py`.\n")

    for label, col in [
        ("overall impact (composite_score)", "impact_rank"),
        ("efficiency (yards per touch)", "efficiency_rank"),
        ("usage (targets_or_touches)", "usage_rank"),
    ]:
        lines.append(f"## Top players by {label}\n")
        top = df.sort_values(col).head(5)
        for _, row in top.iterrows():
            lines.append(
                f"- {row['player_id']} (season {int(row['season'])}, "
                f"pos {row['position_group']}, "
                f"impact_rank={int(row['impact_rank'])}, "
                f"eff_rank={int(row['efficiency_rank'])}, "
                f"usage_rank={int(row['usage_rank'])})"
            )
        lines.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote ground truth table to: {OUT_CSV}")
    print(f"Wrote ground truth summary markdown to: {OUT_MD}")


if __name__ == "__main__":
    main()
